# Generated by Django 4.2.17 on 2026-01-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0026_client_country_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="country_code",
        ),
    ]
