# Generated by Django 4.2.17 on 2026-01-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0027_remove_client_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="country_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("+1", "🇺🇸 United States (+1)"),
                    ("+44", "🇬🇧 United Kingdom (+44)"),
                    ("+91", "🇮🇳 India (+91)"),
                    ("+86", "🇨🇳 China (+86)"),
                    ("+81", "🇯🇵 Japan (+81)"),
                    ("+33", "🇫🇷 France (+33)"),
                    ("+49", "🇩🇪 Germany (+49)"),
                    ("+39", "🇮🇹 Italy (+39)"),
                    ("+34", "🇪🇸 Spain (+34)"),
                    ("+31", "🇳🇱 Netherlands (+31)"),
                    ("+46", "🇸🇪 Sweden (+46)"),
                    ("+47", "🇳🇴 Norway (+47)"),
                    ("+45", "🇩🇰 Denmark (+45)"),
                    ("+358", "🇫🇮 Finland (+358)"),
                    ("+41", "🇨🇭 Switzerland (+41)"),
                    ("+43", "🇦🇹 Austria (+43)"),
                    ("+32", "🇧🇪 Belgium (+32)"),
                    ("+353", "🇮🇪 Ireland (+353)"),
                    ("+61", "🇦🇺 Australia (+61)"),
                    ("+64", "🇳🇿 New Zealand (+64)"),
                    ("+27", "🇿🇦 South Africa (+27)"),
                    ("+234", "🇳🇬 Nigeria (+234)"),
                    ("+254", "🇰🇪 Kenya (+254)"),
                    ("+256", "🇺🇬 Uganda (+256)"),
                    ("+255", "🇹🇿 Tanzania (+255)"),
                    ("+260", "🇿🇲 Zambia (+260)"),
                    ("+263", "🇿🇼 Zimbabwe (+263)"),
                ],
                default="+1",
                max_length=4,
            ),
        ),
    ]
